### PR TITLE
Release v.1.3.0

### PR DESCRIPTION
**Pull request by tjdtls690**
Release v.1.3.0

### CODE REVIEW

**Review by Gilpop8663 — APPROVED** [review]

**Review by jeomxon — APPROVED** [review]
보투게더 파이팅!

**Review by aiaiaiai1 — APPROVED** [review]
🔥 Unexpected token '<', "<html> <h"... is not valid JSON





Unexpected token '<', "<html> <h"... is not valid JSON





Unexpected token '<', "<html> <h"... is not valid JSON





Unexpected token '<', "<html> <h"... is not valid JSON





Unexpected token '<', "<html> <h"... is not valid JSON





Unexpected token '<', "<html> <h"... is not valid JSON





🔥 🔥 🔥 🔥 🔥 🔥

**Review by inyeong-kang — APPROVED** [review]
레전드 보투게더 화이팅~~~!~!~!~~!~!

**Review by chsua — APPROVED** [review]

**Review by woo-chang — APPROVED** [review]
보투게더팀 정말 수고하셨습니다 사랑해요 🫶

**Pull request merged**
